from werkzeug.exceptions import BadRequest
from ..db.models import Datum
from .auth import auth
from sqlalchemy import exc


@auth()
def create(auth_user, body):
    try:
        datum = Datum.create(name=body.get('name'),
                             author=auth_user,
                             type=body.get('type'),
                             mode=body.get('mode'),
                             datum=body.get('datum'))
    except exc.IntegrityError as e:
        err_msg = str(e)
        raise BadRequest(f'Could not add datum: {err_msg}')

    return datum.to_obj(whos_asking=auth_user)
